version: build-{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TARGET_BUILD_VERSION: '0.2.0'

nuget:
  disable_publish_on_pr: true

before_build:
- dotnet --info
- dotnet restore .\src\DotNetSortRefs.sln

build_script:
- dotnet build .\src\DotNetSortRefs.sln --configuration Release /p:Version=%TARGET_BUILD_VERSION%
 
after_test:
  - dotnet pack .\src\DotNetSortRefs --configuration Release /p:Version=%TARGET_BUILD_VERSION%

artifacts:
  - path: '**\dotnet-sort-refs.*.*nupkg' # find all NuGet packages recursively

deploy:
  provider: NuGet
  api_key:
    secure: 6yOBK0JyKMTykW1zW6B4mvc9mgQGnRGex15KG8VhOre/DSTkrUYtgbPCpiBlcX/T
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true

